VersionArgumentIndie:1
VersionArgumentIndieV2:True
IsStar:False
VersionAdvanceRun:powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "{version_indie}Initialize-R48-Visuals.ps1"
VersionAdvanceRunWait:True
