from pathlib import Path
import subprocess,json,hashlib,difflib
R=Path('D:/eva');O=R/'artifacts/rebuild_r45/tracked_bat_log_cleanup_sol_v1';O.mkdir(exist_ok=False)
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();write=lambda p,d:Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
tracked=[p for p in subprocess.check_output(['git','ls-files','-z'],cwd=R).decode('utf8').split('\0')if p];selected=[p for p in tracked if Path(p).suffix.lower()in{'.bat','.log'}];assert len(selected)==12 and not any(Path(p).suffix.lower()=='.log'for p in selected)
protected=list(json.loads((R/'artifacts/rebuild_r45/baseline.json').read_text('utf8'))['original_user_files']);assert len(protected)==15 and 'MUJOCO_LOG.TXT'in protected
scan=[p for p in tracked if (p=='README.md' or p.startswith(('docs/','tools/')))and Path(p).suffix.lower()in{'.md','.py','.ps1','.bat','.json','.toml'}and(R/p).stat().st_size<1000000];scan+= [p.relative_to(R).as_posix()for p in(R/'tools').glob('*r45*.py')if p.relative_to(R).as_posix()not in scan]
needles={p:Path(p).name if 'deployment_'not in p else str(Path(p).parent).replace('\\','/')for p in selected};refs={p:[]for p in selected}
for file in scan:
 text=(R/file).read_text('utf8',errors='replace')
 for line,value in enumerate(text.splitlines(),1):
  normalized=value.lower().replace('\\','/').replace('//','/')
  for name,needle in needles.items():
   if needle.lower()in normalized and len(value)<500:refs[name].append(dict(file=file,line=line,text=value))
reasons={'gradlew.bat':'Required Windows Gradle wrapper','tools/start_test.bat':'Current general development entry; directly called and contract validators read it','tools/start_test_desktop.bat':'Stable desktop shim; delegates current start_test','tools/start_motion_lab.bat':'Existing motion development entry referenced by current documentation','tools/start_pose_lab.bat':'Existing Blender pose development entry with documentation and rebuild delegation','tools/rebuild_pose_lab.bat':'Called by start_pose_lab; reproducible Blender lab build','start_eva_test_r42.bat':'DELETE: Hardlocked R42 world/runtime profiles; only historical R42 manual and legacy R43 cleanup whitelist references; current R45 pipeline does not call it'}
for v in range(25,30):reasons[f'tools/deployment_r{v}/Start-Server.bat']='KEEP: Historical package_release_r'+str(v)+' copies deployment folder. R29 additionally used by R30/R31 and visual installer/PCL templates; preserve reproducible server template chain'
inventory=[dict(path=p,bytes=(R/p).stat().st_size,sha256=sha(R/p),action='DELETE'if p=='start_eva_test_r42.bat'else'KEEP',reason=reasons[p],references=refs[p])for p in selected]
write(O/'audit.json',dict(schema='projectseele.r45.tracked-bat-log-cold-audit.v1',tracked_bat=12,tracked_log=0,delete_paths=['start_eva_test_r42.bat'],tracked_logs_delete=[],keep11_required_wrappers_dev_and_server_templates=True,original15_protected=protected,original15_current_sha256={p:sha(R/p)for p in protected},no_run_or_world_or_history_evidence_scanned_deleted=True,inventory=inventory,git_or_tracked_files_changed_by_child=False))
p=R/'start_eva_test_r42.bat';s=p.read_text('utf8');patch='diff --git a/start_eva_test_r42.bat b/start_eva_test_r42.bat\ndeleted file mode 100644\n'+''.join(difflib.unified_diff(s.splitlines(True),[],fromfile='a/start_eva_test_r42.bat',tofile='/dev/null'))
p=R/'docs/MANUAL_ACCEPTANCE_R42.md';s=p.read_text('utf8');a='- 本机入口 `D:\\eva\\start_eva_test_r42.bat`。`--check` 只检查准备；`--no-shaders` 关闭光影。';b='- 本页保留 R42 历史安装说明；旧版开发快捷入口已退役。复现 R42 使用原批次的 Client.zip／Server.zip。当前开发与安装入口见 [README](../README.md) 及对应批次安装说明。';assert s.count(a)==1;t=s.replace(a,b);patch+='diff --git a/docs/MANUAL_ACCEPTANCE_R42.md b/docs/MANUAL_ACCEPTANCE_R42.md\n'+''.join(difflib.unified_diff(s.splitlines(True),t.splitlines(True),fromfile='a/docs/MANUAL_ACCEPTANCE_R42.md',tofile='b/docs/MANUAL_ACCEPTANCE_R42.md'));(O/'root_delete_obsolete_r42_launcher_and_reference.patch').write_text(patch,encoding='utf8')
write(O/'patch_receipt.json',dict(patch_sha256=sha(O/'root_delete_obsolete_r42_launcher_and_reference.patch'),delete_count1=True,documentation_only_reference_updated=True,original15_touched=False,no_log_evidence_deletion=True,git_index_or_worktree_or_commit_changed_by_child=False,Root_applies_and_updates_Git=True))
(O/'README.zh.md').write_text('只删除 Git 跟踪的 start_eva_test_r42.bat（旧R42专用入口）；更新旧R42手册第7行，把启动入口说明定位为历史批次并链接README。该手册不在原15保护名单。12个tracked BAT中其余11保留：gradlew、5个被旧打包器使用的服务器模板、5个现有开发/桌面/Blender入口。tracked .log（含大小写后缀）=0，不存在需删的tracked log。MUJOCO_LOG.TXT属于原15，保留；artifacts、run和历史原生证据不纳入删除。\n\nR43 cleanup whitelist提到旧R42名称只是旧回退策略，当前R45流程不调用它；不为消除这个历史字面引用而改动其旧清理逻辑。R45当前安装入口/服务器模板由六包的具体payload manifest控制，不能通过清理旧模板目录破坏包依赖。\n\nRoot apply前先 git apply --check 本目录patch；Root可git apply后显式git add -- start_eva_test_r42.bat docs/MANUAL_ACCEPTANCE_R42.md，将删除和引用更新并入本轮统一提交。此代理未apply/删除/暂存/提交。\n',encoding='utf8')
print(json.dumps({'directory':str(O),'delete':['start_eva_test_r42.bat'],'tracked_log':0,'patch_SHA256':sha(O/'root_delete_obsolete_r42_launcher_and_reference.patch')},ensure_ascii=False,indent=2))
