from pathlib import Path
import difflib,json,hashlib
R=Path('D:/eva');O=R/'artifacts/rebuild_r45/lifts_doors_lifecycle_sol_v2/command17_real_button_dispatch_fix_v1';O.mkdir(exist_ok=False);p=R/'src/main/java/com/projectseele/GameEvents.java';s=p.read_text('utf8');a='''        if (event.getHand() == InteractionHand.MAIN_HAND
                && event.getEntity() instanceof ServerPlayer player)
        {
            boolean cleanRebuild =''';b='''        if (event.getHand() == InteractionHand.MAIN_HAND
                && event.getEntity() instanceof ServerPlayer player)
        {
            // Reserve the authored door's passage hold before the vanilla
            // button pulse. Keep vanilla use uncancelled for click/animation.
            if (!player.isSpectator()
                    && CommandRoomSlidingDoorDirector.handleUse(
                            player, event.getPos()))
            {
                return;
            }
            boolean cleanRebuild =''';assert s.count(a)==1;t=s.replace(a,b);(O/'GameEvents.before.txt').write_bytes(p.read_bytes());(O/'GameEvents.candidate.txt').write_text(t,encoding='utf8');rel=p.relative_to(R).as_posix();(O/'root_GameEvents_real_command_door_button_dispatch.patch').write_text(''.join(difflib.unified_diff(s.splitlines(True),t.splitlines(True),fromfile='a/'+rel,tofile='b/'+rel)),encoding='utf8')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();(O/'FROZEN.json').write_text(json.dumps({'source_before_SHA256':sha(p),'patch_SHA256':sha(O/'root_GameEvents_real_command_door_button_dispatch.patch'),'candidate_SHA256':sha(O/'GameEvents.candidate.txt'),'producer_error':'Real ServerPlayer Forge RightClickBlock never dispatches authored command-door handleUse; only old FakePlayer audit directly calls it','all39_registered_inputs_all17_owned_apertures_fixed_by_same_dispatch':True,'original80_tick_passage_hold_unchanged':True,'redstone12_tick_nonshortening_hold_unchanged':True,'vanilla_button_use_cancelled':False,'aperture_owner_identity_or_footprint_changed':False,'permission_reader_or_auto18_policy_changed':False,'shared_Java_world_or_MC_by_child':False},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
actual=R/'artifacts/rebuild_r45/native_facility_session_v1/native_COMMAND17_first_contact_sameQA_v1/ID6_first_contact_160tick.native.json';d=json.loads(actual.read_text('utf8'));fs=d['first_contact_actual_gameTick_frames'];f=d['first_failure']; trace=f['actual_current_trace'];clientLast=fs[-1]['actual_client_collision_sources']
proof=dict(actual_receipt={'path':str(actual),'sha256':sha(actual)},Root_normal_exit0=True,actual_actor_restored=d['actual_actor_restored'],server_button_tick=trace['actual_server_use']['actual_server_tick'],server_button_event_canceled=trace['actual_server_use']['canceled'],server_full_open_tick=trace['after_open_actual']['actual_server_tick'],all29_frames=[dict(server_gameTime=r['actual_server_gameTime'],client_gameTime=r['actual_client_gameTime'],walk_elapsed_ticks=r['actual_server_ticks_since_walk'],hold=r['actual_hold'],six=[c['state']for c in r['actual_six_cells_and_leaves']['actual_complete6_cells']],occupied=r['actual_six_cells_and_leaves']['actual_occupied_entities'],client_horizontal_clip=r['actual_client_collision_sources']['horizontal_sweep_blocked'],server_horizontal_clip=r['actual_server_collision_sources']['horizontal_sweep_blocked'])for r in fs],first_target_close=next(r['actual_server_gameTime']for r in fs if r['actual_hold'][0]['target_progress']==0),first_BARRIER_refill=next(r['actual_server_gameTime']for r in fs if any(c['state']=='minecraft:barrier'for c in r['actual_six_cells_and_leaves']['actual_complete6_cells'])),first_native_assigned_sweep_clip_tick=fs[-1]['actual_server_gameTime'],actual_blocking_client_sources=clientLast['native_aggregate_block_shapes'],actual_entity_shape_sources=clientLast['native_entity_shapes'],actual_TV_virtual_enabled=clientLast['TV_virtual_provider_enabled'],scope='First assigned .15 native shape sweep; not a raw Entity.move input hook',foreign_writer_or_invisible_entity_cause=False,root_cause='Only renewable redstone12 hold exists because real-use80 dispatch is absent; aperture-only occupancy starts after approach and cannot protect a user still 1m outside the plane',fix='Register existing validated handleUse for actual main-hand nonspectator ServerPlayer before broad handlers, preserve vanilla use/click and existing80/12 constants',static_world_fix_needed=False,native_pass_after_fix=False)
(O/'actual_first_close_and_producer.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'directory':str(O),'patch_SHA256':sha(O/'root_GameEvents_real_command_door_button_dispatch.patch')},indent=2))
