from pathlib import Path
import gzip,json,hashlib
R=Path('D:/eva');A=R/'artifacts/rebuild_r45';O=A/'lifts_doors_lifecycle_sol_v2/tv_door_lift_construction_v1/root_v14_cabin558_entry_v1';M=A/'lifts_doors_lifecycle_sol_v2/tv_door_lift_construction_v1/cabin_material_install_v4_source_v14';C=A/'city_transport_xhigh_r45/all10_island_bridge_complete_component_v14_v1';read=lambda p:json.loads(p.read_text('utf8'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));a=[json.loads(l)for l in gzip.open(M/'forward.jsonl.gz','rt',encoding='utf8')];b=[json.loads(l)for l in gzip.open(C/'forward.jsonl.gz','rt',encoding='utf8')];aa={tuple(r['pos'])for r in a};bb={tuple(r['pos'])for r in b};assert len(aa)==558 and len(bb)==100 and not aa&bb
proof=dict(schema='projectseele.city100-cabin558-frozen-v14-conflict-proof.v1',components=[ref(M/'forward.jsonl.gz'),ref(M/'inverse.jsonl.gz'),ref(C/'forward.jsonl.gz'),ref(C/'inverse.jsonl.gz')],source_world=str(A/'composition_candidates/R45_source_candidate_20261004_station_finish_v14_01/world'),source_actual_receipt=ref(A/'composition_candidates/R45_source_candidate_20261004_station_finish_v14_01/composition_station_finish_readback.json'),unique_static_cells=658,coordinate_overlap=[],cabin_metadata_changes=0,cabin_BE_changes=0,qualityWalk40_owned_by_City=True,shape_cache_three_key_derived_candidates_PENDING_ACTUAL_CAPTURE=True,material_Root_sources_resources_compiled216=True,material_world_installed=False,Java_or_world_or_shared_source_by_child=False)
(O/'combined658_coordinate_conflict_proof.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(O/'ROOT_ORDER_CURRENT.zh.md').write_text('''当前正式源为 v14_01，1739文件；不是旧v13整体SHA。Root已经合入558三材质登记、四源维护修复、17资源/语言键，并实际编译216。世界558尚未安装。已合屋顶识别修复不重复套用；不把源码/资源状态再写成pending。\n\n与City100牌完整batch共享同一个不可变v14源。实际坐标交集为空、658个唯一static cells。City负责quality_walk_cases原bytes+40请求及联合root writer：一条命令只复制一次v14完整Source，再应用100+558；不用QA region/进度。此目录catalog.UNBOUND.json包含558完整正逆/精确map/1739baseline，但没有猜测新3state native traits。\n\nRoot先实际统一编译并启动已准备ID6首接触1lane（0photo/≤160server ticks）；同一个C17初始化只读输出3个registered state的native collision+outline/hasBE/loadedclassSHA。收到真实文件后：\n```powershell\npython D:/eva/tools/bind_cabin558_actual_registry_r45.py --capture D:/eva/artifacts/rebuild_r45/native_facility_session_v1/native_COMMAND17_first_contact_sameQA_v1/cabin_registered_materials.native.json --out D:/eva/artifacts/rebuild_r45/lifts_doors_lifecycle_sol_v2/tv_door_lift_construction_v1/root_v14_cabin558_entry_v1/native_actual_binding_v1\n```\n绑定器只生成离线工件；核实际FML/source绑定和loaded byteSHA，再生成native_state_traits.actual_merged.json/3key碰撞与轮廓追加/catalog.BOUND。不从声明或字符串存在假定native。City联合入口采用BOUND里独立558 component及native traits；生成明确3key cache派生payload完整正逆，原图其余keys不变。最终world全量回读必须包含658、全部原BE、qualityWalk40以及派生cache；物理17门/native90/165/BE17仅各自有限继承，不虚构新全链通过。\n\n轿厢几何/地板/门口/按钮/原6BE保持。399顶棚+159人员车墙，仅3独立plain fullcube材料；无模型变更、无新灯具占用净空。美术观感、战斗驾驶、服务器实际验收已由用户要求亲自承担；保留这些尚未测/认可字段。\n''',encoding='utf8')
status=A/'lifts_doors_lifecycle_sol_v2/current_status_20261004_cabin216_ID6_160_v1';status.mkdir(exist_ok=False)
(status/'CURRENT.json').write_text(json.dumps(dict(source='v14_01 actual1739',current_source_receipt=proof['source_actual_receipt'],Root_material_sources_resources_compiled216=True,material_world558_installed=False,Root_probe_v2_and_sameQA_addendum_applied=True,Root_material_capture_delta_compile_PENDING=True,ID6_remaining_contact_cause='UNKNOWN until one native assigned-sweep witness',old_short_v13_actual0_of1_restore12ticks_true_photos2_of3=True,new_ID6_job='same restored QA; max160 actual server ticks after staging ACK; no photos/full141; Root launch only',cabin_static658_withCity_coordinates_disjoint=True,native_shape3_binding_pending_real_capture=True,old90_24_and165_andBE17_scopes_retained_not_repeated=True,visual_combat_driving_server_review_by_user=True,refs=[ref(R/'tools/prepare_command17_first_contact_sameQA_r45.py'),ref(R/'tools/bind_cabin558_actual_registry_r45.py'),ref(O/'combined658_coordinate_conflict_proof.json'),ref(O/'catalog.UNBOUND.json')],child_Java_MC_world_or_shared_source_written=False),ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'coordinate_conflict_receipt':ref(O/'combined658_coordinate_conflict_proof.json'),'binder':ref(R/'tools/bind_cabin558_actual_registry_r45.py'),'status':str(status/'CURRENT.json')},indent=2))

