from pathlib import Path
import json,gzip,hashlib
R=Path('D:/eva');A=R/'artifacts/rebuild_r45';O=A/'lifts_doors_lifecycle_sol_v2/tv_door_lift_construction_v1/root_v14_cabin558_entry_v1';O.mkdir(exist_ok=False);M=A/'lifts_doors_lifecycle_sol_v2/tv_door_lift_construction_v1/cabin_material_install_v4_source_v14';W=A/'composition_candidates/R45_source_candidate_20261004_station_finish_v14_01/world'
read=lambda p:json.loads(Path(p).read_text('utf8'));sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();write=lambda p,d:Path(p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8');ref=lambda p:dict(path=Path(p).relative_to(R).as_posix(),sha256=sha(p))
actual=read(W.parent/'composition_station_finish_readback.json');write(O/'source_v14_full_baseline.json',dict(source_world=str(W),files=actual['full_after_inventory']));rows=[json.loads(l)for l in gzip.open(M/'forward.jsonl.gz','rt')];assert len(rows)==558
write(O/'exact558_rows.json',{';'.join(map(str,r['pos'])):r for r in rows})
base=read(A/'lifts_doors_lifecycle_sol_v2/tv_door_lift_construction_v1/root_v12_entry_v2/catalog.json');core=base['core'];codec=base['codec'];oldTraits=base['native_state_contract'];pid='tv_cabin7_original_material558'
cat=dict(schema='projectseele.r45.tv-current-v14-cabin558.v1',source=str(W.relative_to(R)),baseline=ref(O/'source_v14_full_baseline.json'),actual_root_v14_receipt=ref(W.parent/'composition_station_finish_readback.json'),core=core,codec=codec,native_state_contract=None,prior_native_traits=oldTraits,exact_rows=ref(O/'exact558_rows.json'),identity_file=base['identity_file'],seed=base['seed'],world_uuid=base['world_uuid'],dimension=base['dimension'],default_components=[pid],allowed_file_targets=[],components=[dict(id=pid,classification='CLASSIFIED_CANDIDATE_NOT_NATIVE',owner_prefixes=['tv_lift_material/'],patches=[dict(forward=ref(M/'forward.jsonl.gz'),inverse=ref(M/'inverse.jsonl.gz'),rows=558)],files=[])],epochs=[ref(p)for p in[M/'FROZEN.json',M/'all7_current_style_full_material_components.json',M/'protected_actual_BEs_and_inputs.json',M/'root_register_materials_and_recurrence_producer.patch',*sorted(M.rglob('*.candidate.txt')),*sorted((M/'resource_overlay').rglob('*'))]if p.is_file()],state_capture_REQUIRED_PENDING=True,Root_compiled216_sources_resources=True,world558_installed=False)
write(O/'catalog.UNBOUND.json',cat)
(O/'catalog.UNBOUND.json.sha256').write_text(sha(O/'catalog.UNBOUND.json')+'\n',encoding='ascii');print(O)
