"""Prepare fixed actual actor palettes for full retained-body/additive-socket review."""
from pathlib import Path
import argparse,hashlib,json,numpy as np
from replay_rigged_angel_witness_r44 import skin
ap=argparse.ArgumentParser();ap.add_argument('--candidate',type=Path,required=True);ap.add_argument('--original-witness',type=Path,required=True);ap.add_argument('--new-witness',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);args=ap.parse_args();args.out.mkdir(parents=True,exist_ok=True);candidate=json.loads(args.candidate.read_text());raw=np.asarray(candidate['parts']['root']['vertices'],np.float32).reshape(-1,8);points=raw[:,:3].astype(float)*[-1/16,1/16,1/16];ids=np.asarray(candidate['skin']['indices']).reshape(-1,4);weights=np.asarray(candidate['skin']['weights']).reshape(-1,4);rows=[]
sets=[(args.original_witness,'4e6d4a03-3d47-4783-9f6c-78eb7c566f76',{'first_down':4190581,'shoulder_first_error':4190600,'recovery':4190662,'recovery_handoff':4190698,'second_down':4190780}),(args.original_witness,'73eafc1d-b5ea-4d17-913f-04f24e057419',{'retired_fixture_negative':4190801}),(args.new_witness,'c2d0a3bb-b550-42bd-aeac-1fc04b33c1e5',{'upper_back_first_error':4191936,'arm_cap_first_error':4191643})]
for witness,actor,requested in sets:
    selected={};identity=None
    for line in witness.open(encoding='utf8'):
        row=json.loads(line)
        if row.get('kind')=='actual-parsed-weighted-resource':identity=row;assert np.array_equal(raw[:len(np.asarray(row['decoded_vertices']).reshape(-1,8))],np.asarray(row['decoded_vertices'],np.float32).reshape(-1,8));assert row['bones']==candidate['skin']['bones']
        elif row.get('kind')=='actual-weighted-emit-vertices'and row['entity_uuid']==actor:
            for label,tick in requested.items():
                gap=abs(row['game_time']-tick)
                if label not in selected or gap<selected[label][0]:selected[label]=(gap,row)
    assert identity and len(selected)==len(requested)
    for label,(gap,row)in selected.items():
        palette=row['actual_palette'];matrices=np.asarray([p['actual_root_relative_matrix_column_major']for p in palette]).reshape(-1,4,4).transpose(0,2,1);real=np.asarray([p['actual_real_quaternion_xyzw']for p in palette])[:,[3,0,1,2]];dual=np.asarray([p['actual_dual_quaternion_xyzw']for p in palette])[:,[3,0,1,2]];scaled=np.asarray([p['scaled_lbs_branch']for p in palette]);world=np.asarray(row['actual_emit_to_world_matrix_column_major']).reshape(4,4).T;lift=np.asarray(row.get('actual_ground_support_translation_emit_xyz',[0,0,0]));new=skin(points,ids,weights,real,dual,matrices,scaled,'first-slot')[0];new_world=(new+lift)@world[:3,:3].T+world[:3,3];old_world=np.asarray(row['vertices_world_xyz']).reshape(-1,3);old_raw=np.asarray(identity['decoded_vertices'],np.float32).reshape(-1,8);path=args.out/(label+'.npz');np.savez_compressed(path,old_world=old_world,new_world=new_world,world=world,uv=old_raw[:,3:5],old_uv=old_raw[:,3:5],new_uv=raw[:,3:5],neutral_emit=points,new_emit=new)
        info=dict(label=label,actor_uuid=actor,actual_game_time=row['game_time'],actual_frame=row['frame'],requested_tick=requested[label],tick_delta=gap,file=str(path.resolve()),original_visible_vertices_retained=len(old_raw),added_vertices=len(raw)-len(old_raw),old_world_minimum_y=float(old_world[:,1].min()),new_world_minimum_y_reusing_original_shift=float(new_world[:,1].min()),actual_first_error_edge_before_metres=float(np.linalg.norm(old_world[20796]-old_world[20797])),actual_first_error_edge_after_metres=float(np.linalg.norm(new_world[20796]-new_world[20797])),upper_back9580_edge_before_metres=float(np.linalg.norm(old_world[28740]-old_world[28741])),upper_back9580_edge_after_metres=float(np.linalg.norm(new_world[28740]-new_world[28741])));rows.append(info)
(args.out/'actual_state_views.json').write_text(json.dumps(dict(rows=rows,candidate=str(args.candidate.resolve()),candidate_sha256=hashlib.sha256(args.candidate.read_bytes()).hexdigest(),scope='Exact separate recorded actors and fixed native palettes/world/ground shift; original full visible geometry/UV/normals preserved as exact prefix, additive sockets only. New geometry has not run natively; original mesh ground shift reused, no new offline minimum lift. Retired QA fixture is a negative-control pose, not a second AI or native current actor.'),indent=2));print(json.dumps(rows,indent=2))
