"""CPU render fixed real palette/geometry under explicit alternate blend rules."""
from pathlib import Path
import argparse,json,sys
import bpy,numpy as np
from mathutils import Vector

ROOT=Path(__file__).resolve().parents[1]
ap=argparse.ArgumentParser();ap.add_argument('--audit',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);args=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);args.out.mkdir(parents=True,exist_ok=True)
data=np.load(args.audit/'largest_original_policy_separation.npz',allow_pickle=False);palette=json.loads((args.audit/'largest_original_palette.json').read_text('utf8'));fixture=json.loads((ROOT/'artifacts/rebuild_r44/combat/tv_exchange/counter_v13/fixture.json').read_text('utf8'))['actors'][1];raw=json.loads((ROOT/'artifacts/rebuild_r44/combat/tv_exchange/counter_v13/bind_region/palm_transitions_canonical_C6/overlay/assets/projectseele/mesh/sachiel.mesh.json').read_text('utf8'))['parts']['root']['vertices'];uv=np.asarray(raw).reshape(-1,8)[:,3:5]
world=data['world'];axes=np.array([[1.,0,0],[0,0,-1],[0,1,0]]);native_world=data['actual_native_emit']@world[:3,:3].T+world[:3,3];origin=(native_world.min(0)+native_world.max(0))*.5;policies=('first_slot','dominant','running_sum','running_weight_descending');posed={p:((data[p]+data['actual_lift_emit'])@world[:3,:3].T+world[:3,3]-origin)@axes.T for p in policies};allpoints=np.concatenate(list(posed.values()));centre=Vector((allpoints.min(0)+allpoints.max(0))*.5);span=float(np.ptp(allpoints,axis=0).max());rows=[]
for policy in policies:
    bpy.ops.wm.read_factory_settings(use_empty=True);scene=bpy.context.scene;mesh=bpy.data.meshes.new('Actual parsed original triangles');points=posed[policy];mesh.from_pydata(points.tolist(),[],np.arange(len(points)).reshape(-1,3).tolist());mesh.update();obj=bpy.data.objects.new('Actual parsed original triangles',mesh);bpy.context.collection.objects.link(obj);layer=mesh.uv_layers.new(name='Actual original UV');
    for loop in mesh.loops:layer.data[loop.index].uv=(uv[loop.vertex_index,0],1-uv[loop.vertex_index,1])
    mat=bpy.data.materials.new('Actual original texture');mat.use_nodes=True;mat.node_tree.nodes.clear();shader=mat.node_tree.nodes.new('ShaderNodeBsdfPrincipled');output=mat.node_tree.nodes.new('ShaderNodeOutputMaterial');texture=mat.node_tree.nodes.new('ShaderNodeTexImage');texture.image=bpy.data.images.load(fixture['texture'],check_existing=True);mat.node_tree.links.new(texture.outputs['Color'],shader.inputs['Base Color']);mat.node_tree.links.new(shader.outputs['BSDF'],output.inputs['Surface']);shader.inputs['Roughness'].default_value=.8;mesh.materials.append(mat)
    scene.world=bpy.data.worlds.new('Diagnostic background');scene.world.color=(.13,.15,.18);light_data=bpy.data.lights.new('Fixed comparison area','AREA');light_data.energy=65000;light_data.size=70;light=bpy.data.objects.new('Fixed comparison area',light_data);bpy.context.collection.objects.link(light);light.location=centre+Vector((20,-40,60));light.rotation_euler=(centre-light.location).to_track_quat('-Z','Y').to_euler()
    cam_data=bpy.data.cameras.new('Fixed comparison camera');camera=bpy.data.objects.new('Fixed comparison camera',cam_data);bpy.context.collection.objects.link(camera);scene.camera=camera;cam_data.type='ORTHO';cam_data.ortho_scale=span*1.8
    scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=4;scene.cycles.max_bounces=1;scene.cycles.use_denoising=True;scene.render.threads_mode='FIXED';scene.render.threads=2;scene.render.resolution_x=960;scene.render.resolution_y=720;scene.render.resolution_percentage=100
    for view,direction in(('front',(1,-2,.6)),('back',(-1,2,.6))):
        camera.location=centre+Vector(direction).normalized()*span*3;camera.rotation_euler=(centre-camera.location).to_track_quat('-Z','Y').to_euler();file=args.out/(policy+'_'+view+'.png');scene.render.filepath=str(file);bpy.ops.render.render(write_still=True);rows.append(dict(policy=policy,view=view,file=str(file),actual_frame=palette['frame'],game_time=palette['game_time'],vertices=len(points),camera_center=list(centre),camera_scale=cam_data.ortho_scale))
(args.out/'fixed_original_weights_render_receipt.json').write_text(json.dumps(dict(rows=rows,source_policy='original fixed decoded weights; source C6 only supplies identical original geometry/UV; no C6 weight substitutions',scope='Actual parsed original geometry, real recorded CPU bone/DQ palette, original UV/texture. All methods retain the same world transform and ground lift. Alternate algorithms are offline candidates; game raster, normal treatment, terrain resupport and artistic acceptance remain unverified.'),indent=2),'utf8');print('Completed actual fixed palette comparison',args.out,flush=True)
