"""CPU-only paired task review; the recorded receiver is explicitly frozen."""
from pathlib import Path
import argparse,json,sys
import bpy,numpy as np
from mathutils import Vector
ap=argparse.ArgumentParser();ap.add_argument('--out',type=Path,required=True);ap.add_argument('--width',type=int,default=768);args=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);out=args.out.resolve();fixture=json.loads((out/'fixture.json').read_text());task=fixture['actual_low_receiver_task'];data=fixture['actors'][0];name=data['name'];scene=bpy.context.scene;directory=out/'paired_cpu_task_review';directory.mkdir(exist_ok=True);receiver=np.load(Path(task['receiver_directory'])/'receiver_full_surface.npz')['vertices_actor_dcc'];mesh=bpy.data.meshes.new('Recorded receiver full submitted triangles');mesh.from_pydata(receiver.tolist(),[],np.arange(len(receiver)).reshape(-1,3).tolist());mesh.update();obj=bpy.data.objects.new('FROZEN_ACTUAL_RECEIVER_NO_REACTION',mesh);bpy.context.collection.objects.link(obj);mat=bpy.data.materials.new('Recorded receiver diagnostic amber');mat.diffuse_color=(.36,.13,.025,1);mat.use_nodes=True;mat.node_tree.nodes.clear();bsdf=mat.node_tree.nodes.new('ShaderNodeBsdfPrincipled');bsdf.inputs['Base Color'].default_value=mat.diffuse_color;material_output=mat.node_tree.nodes.new('ShaderNodeOutputMaterial');mat.node_tree.links.new(bsdf.outputs['BSDF'],material_output.inputs['Surface']);mesh.materials.append(mat)
scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=3;scene.cycles.use_denoising=True;scene.cycles.max_bounces=2;scene.render.threads_mode='FIXED';scene.render.threads=2;scene.render.resolution_x=args.width;scene.render.resolution_y=round(args.width*9/16);scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG';camera=scene.camera;camera.animation_data_clear();camera.data.type='ORTHO';camera.data.ortho_scale=89.;centre=Vector((0,13,21));camera.location=centre+Vector((95,-74,56));camera.rotation_euler=(centre-camera.location).to_track_quat('-Z','Y').to_euler();rows=json.loads((out/'contact_pass_receipt.json').read_text())['records'];receipt=[]
for segment in task['segments']:
    selected=[r['frame']for r in rows if r['label']==segment['label']and r['raw_frame']is not None];indices=sorted(set([selected[0],selected[len(selected)//4],segment['contact_frame'],selected[len(selected)*3//4],selected[-1]]))
    for frame in indices:
        scene.frame_set(frame);bpy.context.view_layer.update();scene.render.filepath=str(directory/(segment['label']+f'_{frame:04d}.png'));bpy.ops.render.render(write_still=True);receipt.append(dict(label=segment['label'],frame=frame,path=scene.render.filepath,receiver_frozen=True));print('Paired low source task frame',frame,flush=True)
(directory/'actual_cpu_task_review.json').write_text(json.dumps(dict(frames=receipt,receiver_frozen=True,receiver_task_source=task['receiver_directory'],review_scope='Saved evaluated complete EVA source task plus frozen actual native receiver triangles. No target reaction, active AI, runtime layer or dynamic force acceptance.'),indent=2))
