"""CPU full-body and shoulder seam pictures of the exact prepared real states."""
from pathlib import Path
import argparse,json,sys,bpy,numpy as np
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[1]
ap=argparse.ArgumentParser();ap.add_argument('--states',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);args=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);args.out.mkdir(parents=True,exist_ok=True);contract=json.loads((args.states/'actual_state_views.json').read_text('utf8'));fixture=json.loads((ROOT/'artifacts/rebuild_r44/combat/tv_exchange/counter_v13/fixture.json').read_text('utf8'))['actors'][1];axes=np.array([[1.,0,0],[0,0,-1],[0,1,0]]);rows=[]
for record in contract['rows']:
    data=np.load(record['file'],allow_pickle=False);origin=data['world'][:3,3];world_points={p:(data[p+'_world']-origin)@axes.T for p in('old','new')};union=np.concatenate(list(world_points.values()));whole_center=Vector((union.min(0)+union.max(0))*.5);whole_scale=float(np.ptp(union,axis=0).max())*1.8
    focus=[28740,28741,28742]if record['label']=='upper_back_first_error'else[28806,28807,28808]if record['label']=='arm_cap_first_error'else[20796,20797,20798]
    local=np.concatenate([p[focus]for p in world_points.values()]);local_center=Vector((local.min(0)+local.max(0))*.5);local_scale=max(8.,float(np.ptp(local,axis=0).max())*1.8+4.)
    for policy in('old','new'):
        bpy.ops.wm.read_factory_settings(use_empty=True);scene=bpy.context.scene;points=world_points[policy];mesh=bpy.data.meshes.new('Exact original topology');mesh.from_pydata(points.tolist(),[],np.arange(len(points)).reshape(-1,3).tolist());mesh.update();obj=bpy.data.objects.new('Exact original topology',mesh);bpy.context.collection.objects.link(obj);uv=mesh.uv_layers.new(name='Original source UV')
        uv_values=data[policy+'_uv']if policy+'_uv'in data else data['uv']
        for loop in mesh.loops:uv.data[loop.index].uv=(uv_values[loop.vertex_index,0],1-uv_values[loop.vertex_index,1])
        mat=bpy.data.materials.new('Original texture');mat.use_nodes=True;mat.node_tree.nodes.clear();shader=mat.node_tree.nodes.new('ShaderNodeBsdfPrincipled');output=mat.node_tree.nodes.new('ShaderNodeOutputMaterial');texture=mat.node_tree.nodes.new('ShaderNodeTexImage');texture.image=bpy.data.images.load(fixture['texture'],check_existing=True);mat.node_tree.links.new(texture.outputs['Color'],shader.inputs['Base Color']);mat.node_tree.links.new(shader.outputs['BSDF'],output.inputs['Surface']);shader.inputs['Roughness'].default_value=.8;mesh.materials.append(mat)
        scene.world=bpy.data.worlds.new('Diagnostic environment');scene.world.color=(.15,.17,.20);light_data=bpy.data.lights.new('Fixed area','AREA');light_data.energy=85000;light_data.size=80;light=bpy.data.objects.new('Fixed area',light_data);bpy.context.collection.objects.link(light);light.location=whole_center+Vector((20,-30,55));light.rotation_euler=(whole_center-light.location).to_track_quat('-Z','Y').to_euler()
        cam_data=bpy.data.cameras.new('Fixed matching camera');cam=bpy.data.objects.new('Fixed matching camera',cam_data);bpy.context.collection.objects.link(cam);scene.camera=cam;cam_data.type='ORTHO';scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=2;scene.cycles.max_bounces=1;scene.cycles.use_denoising=True;scene.render.threads_mode='FIXED';scene.render.threads=2;scene.render.resolution_x=800;scene.render.resolution_y=600;scene.render.resolution_percentage=100
        for view,centre,scale in [('whole',whole_center,whole_scale)]+([('shoulder',local_center,local_scale)]if record['label']in('shoulder_first_error','upper_back_first_error','arm_cap_first_error')else[]):
            cam_data.ortho_scale=scale;direction=Vector((1,-2,.8)).normalized();cam.location=centre+direction*scale*3;cam.rotation_euler=(centre-cam.location).to_track_quat('-Z','Y').to_euler();path=args.out/(record['label']+'_'+policy+'_'+view+'.png');scene.render.filepath=str(path);bpy.ops.render.render(write_still=True);rows.append(dict(**record,policy=policy,view=view,picture=str(path),same_camera_center=list(centre),same_camera_scale=scale))
(args.out/'actual_binding_state_render_receipt.json').write_text(json.dumps(dict(rows=rows,scope=contract['scope']+' CPU images use identical original texture, source UV, topology and matching cameras; GPU/shader/native collision/artist acceptance unverified.'),indent=2),'utf8');print('Completed exact state images',args.out,flush=True)
