"""CPU review of original full geometry and explicitly labelled UV shell."""
from pathlib import Path
import argparse,json,sys
import bpy,numpy as np
from mathutils import Vector
ap=argparse.ArgumentParser();ap.add_argument('--parts',type=Path,required=True);args=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);p=args.parts.resolve();report=json.loads((p/'source_part_topology.json').read_text());data=np.load(p/'original_geometry_with_parts.npz');v=data['vertices_source'];points=v[:,[0,2,1]]*[1,-1,1];source_indices=np.flatnonzero(np.char.find(data['face_material'].astype(str),'6b823')!=0);tri=data['triangles'][source_indices];uv=data['uv_per_triangle'][source_indices];materials=data['face_material'][source_indices];groups=data['face_uv_component'][source_indices];bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
mesh=bpy.data.meshes.new('Original all source visible triangles');mesh.from_pydata(points.tolist(),[],tri.tolist());mesh.update();layer=mesh.uv_layers.new(name='Original UV');obj=bpy.data.objects.new('FULL ORIGINAL SOURCE NO FACES DELETED',mesh);bpy.context.collection.objects.link(obj);texture_material={};root=Path(report['source']).parent
for name in sorted(set(materials)):
    mat=bpy.data.materials.new(name);mat.use_nodes=True;mat.node_tree.nodes.clear();bsdf=mat.node_tree.nodes.new('ShaderNodeBsdfPrincipled');output=mat.node_tree.nodes.new('ShaderNodeOutputMaterial');mat.node_tree.links.new(bsdf.outputs['BSDF'],output.inputs['Surface']);image=mat.node_tree.nodes.new('ShaderNodeTexImage');image.image=bpy.data.images.load(str(root/(name.replace('.001',''))));mat.node_tree.links.new(image.outputs['Color'],bsdf.inputs['Base Color']);bsdf.inputs['Roughness'].default_value=.65;texture_material[name]=len(mesh.materials);mesh.materials.append(mat)
for color,label in(((.015,.3,.85,1),'UV721 source cap shell'),((1.,.015,.005,1),'actual face9580 ancestry')):
    mat=bpy.data.materials.new(label);mat.use_nodes=True;mat.node_tree.nodes.clear();bsdf=mat.node_tree.nodes.new('ShaderNodeBsdfPrincipled');bsdf.inputs['Base Color'].default_value=color;output=mat.node_tree.nodes.new('ShaderNodeOutputMaterial');mat.node_tree.links.new(bsdf.outputs['BSDF'],output.inputs['Surface']);mesh.materials.append(mat)
for i,face in enumerate(mesh.polygons):
    face.material_index=texture_material[materials[i]]
    for j,loop in enumerate(face.loop_indices):layer.data[loop].uv=uv[i,j]
scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=12;scene.cycles.use_denoising=True;scene.render.threads_mode='FIXED';scene.render.threads=2;scene.render.resolution_x=768;scene.render.resolution_y=768;scene.render.resolution_percentage=100;scene.world.color=(.08,.08,.08);camera_data=bpy.data.cameras.new('Source part camera');camera=bpy.data.objects.new('Source part camera',camera_data);bpy.context.collection.objects.link(camera);scene.camera=camera;camera_data.type='ORTHO'
for position,power,size in(((10,-18,24),2200,14),((-12,-5,18),1100,12),((0,15,24),1800,14)):
    light_data=bpy.data.lights.new('Source shape area','AREA');light_data.energy=power;light_data.shape='DISK';light_data.size=size;light=bpy.data.objects.new(light_data.name,light_data);bpy.context.collection.objects.link(light);light.location=position;light.rotation_euler=(Vector((0,0,10))-light.location).to_track_quat('-Z','Y').to_euler()
rows=[]
for label,position,centre,scale,highlight in(('neutral_full_front',(20,-35,18),(0,0,8),21,False),('neutral_full_back',(20,35,18),(0,0,8),21,False),('neutral_cap_back_labelled',(12,23,17),(0,0,13.6),10,True),('neutral_cap_front_labelled',(12,-23,17),(0,0,13.6),10,True)):
    for i,face in enumerate(mesh.polygons):face.material_index=len(texture_material)+1 if highlight and source_indices[i]==report['original_source_face']else len(texture_material)if highlight and materials[i]==report['material']and groups[i]==report['uv_component_id']else texture_material[materials[i]]
    camera.location=position;camera.rotation_euler=(Vector(centre)-camera.location).to_track_quat('-Z','Y').to_euler();camera_data.ortho_scale=scale;scene.render.filepath=str(p/(label+'.png'));bpy.ops.render.render(write_still=True);rows.append(dict(label=label,file=scene.render.filepath,all_source_faces_present=len(tri),highlight_source_uv_component=report['uv_component_id']if highlight else None));print('Original full source part view',label,flush=True)
(p/'source_part_cpu_review.json').write_text(json.dumps(dict(rows=rows,scope='Exact original source geometry/UV, full faces retained. Blue identifies UV island721, red identifies original face2395; colours are diagnostics only, not a binding result.'),indent=2))
